require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

Style/CaseEquality:
  Enabled: false
